all:
	g++ generator.cc generator-test.cc -o generator

clean:
	rm -f generator

#include ../sudoku.mk

#TESTFILES = generator-test

#OBJFILES = file-parser.o generator.o sudoku-problem.o

#LIBNAME = sudoku-generator

#ADDLIBS =

#include ../makefiles/default_rules.mk
