all:
	gcc generator.cc -o generator.o

include ../sudoku.mk

#TESTFILES = generator-test

#OBJFILES = file-parser.o generator.o sudoku-problem.o

#LIBNAME = sudoku-generator

#ADDLIBS =

include ../makefiles/default_rules.mk
