
all:

EXTRA_CXXFLAGS = -Wno-sign-compare
include ../sudoku.mk

BINFILES = eval-mpi-throughput eval-serial-throughput eval-omp-throughput

OBJFILES =

TESTFILES =

ADDLIBS = 

include ../makefiles/default_rules.mk
