
all:

EXTRA_CXXFLAGS = -Wno-sign-compare
include ../sudoku.mk

BINFILES = validate 

OBJFILES =

TESTFILES =

ADDLIBS = ../util/sudoku-util.a ../solver/sudoku-solver.a ../generator/sudoku-generator.a ../validator/sudoku-validator.a

include ../makefiles/default_rules.mk
