all:


include ../sudoku.mk

TESTFILES = solver-test

OBJFILES = solver-omp.o solver-serial.o solver-mpi.o

LIBNAME = sudoku-solver

ADDLIBS = ../util/sudoku-util.a

include ../makefiles/default_rules.mk
