
all:

EXTRA_CXXFLAGS = -Wno-sign-compare
include ../sudoku.mk

BINFILES = generate-sudoku

OBJFILES =

TESTFILES = generator-test

ADDLIBS = ../generator/sudoku-generator.a ../util/sudoku-util.a

include ../makefiles/default_rules.mk
